### ISSUE TITLE
When will the dataset be released?

### ISSUE THREAD

**Issue by xyl-507** [Lich-King000/UAVNLT#1]
Hello, author. 
Thanks for your contributions. 
I want to FOLLOW your work and wonder if there are any plans to publish the dataset?

**Comment by Lich-King000** [comment]
Hello, thank you for your folow. Due to some chores, we are going to release the dataset by 7.10.  You will be notified at that time.

**Comment by xyl-507** [comment]
@Lich-King000 
Thanks！If you can, it is best to have a Baidu web disk link.

**Comment by xyl-507** [comment]
@Lich-King000 
Excuse me, has the plan been delayed?
